services:
  - type: web
    name: fastlife
    env: node
    buildCommand: npm install && npx prisma generate
    startCommand: npx prisma migrate deploy && node prisma/seed.js && node app.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
    autoDeploy: true
